<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="firefighter">

  <!-- From urdf/tutorials/using xacro to clean up a urdf file -->

  <!-- use xacro property -->
  <xacro:property name="width" value=".2" />
  <xacro:property name="bodylen" value=".6" />
  <link name="base_link">
    <visual>
      <geometry>
        <cylinder radius="${width}" length="${bodylen}"/>
      </geometry>
      <material name="blue">
        <color rgba="0 0 .8 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${width}" length="${bodylen}"/>
      </geometry>
    </collision>
  </link>

  
  <!-- basic macro -->
  <xacro:macro name="default_origin">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:macro>
  <xacro:default_origin />

  <!-- add parameters  -->
  <xacro:macro name="default_inertial" params="mass">
    <inertial>
      <mass value="${mass}" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0"
               iyy="1.0" iyz="0.0"
               izz="1.0" />
    </inertial>
  </xacro:macro>
  <xacro:default_inertial mass="10"/>

  <!-- block as param -->
  <xacro:macro name="blue_shape" params="name *shape">
    <link name="${name}">
      <visual>
        <geometry>
          <xacro:insert_block name="shape" />
        </geometry>
        <material name="blue">
          <color rgba="0 0 .8 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <xacro:insert_block name="shape" />
        </geometry>
      </collision>
    </link>
  </xacro:macro>

  <xacro:blue_shape name="base_link">
    <cylinder radius=".42" length=".01" />
  </xacro:blue_shape>


  <!-- multiple similar looking macro -->
  
  <xacro:macro name="leg" params="prefix reflect">
    <link name="${prefix}_leg">
      <visual>
        <geometry>
          <box size="${leglen} .2 .1"/>
        </geometry>
        <origin xyz="0 0 -${leglen/2}" rpy="0 ${pi/2} 0"/>
        <material name="white">
          <color rgba="1 1 1 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <box size="${leglen} .2 .1"/>
        </geometry>
        <origin xyz="0 0 -${leglen/2}" rpy="0 ${pi/2} 0"/>
      </collision>
      <xacro:default_inertial mass="10"/>
    </link>

    <joint name="base_to_${prefix}_leg" type="fixed">
      <parent link="base_link"/>
      <child link="${prefix}_leg"/>
      <origin xyz="${reflect*(width+.02)} 0 .25" />
    </joint>
    <!-- A bunch of stuff cut -->
  </xacro:macro>

  <xacro:property name="leglen" value="0.5" />
  <xacro:property name="pi" value="3.1415926" />
  <!-- right leg -->
  <xacro:leg prefix="right" reflect="1" />

  <!-- left leg -->
  <xacro:leg prefix="left" reflect="-1" />
  
</robot>